title: "Creating an All-In-One Network Appliance"
author: "Mat Kenner"
description: "Here is an enterprise-level network appliance at a consumer level pricetag." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.
email: "matdkenner@gmail.com"
twitter_username: "MatKenner"
github_username: "MatKenner"
linkedin_username: "MatKenner"
#facebook_username: MatKenner
#flickr_username: #username
#instagram_username: MatKenner
#pinterest_username: MatKenner
#youtube_username: MatKenner
#googleplus_username: #+username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
